import { MapType } from '../dto/map-type';
import CircleAlterOptions from '../features/circle/circle-alter-options';
import CircleOptions from '../features/circle/circle-options';
import GeoJsonOptions from '../features/geojson/geojson-options';
import CircleMarkerOptions from '../features/marker/circle-marker-options';
import MarkerAlterOptions from '../features/marker/marker-alter-options';
import MarkerOptions from '../features/marker/marker-options';
import PolygonAlterOptions from '../features/polygons/polygon-alter-options';
import PolygonOptions from '../features/polygons/polygon-options';
import PolylineOptions from '../features/polyline/polyline-options';
import PopupOptions from '../features/popup/popup-options';
import IMapFunctions from './mapFunctions';
export default class Leaflet implements IMapFunctions {
    private map;
    private leaflet;
    private position;
    private mapsApiLoader;
    private selectedPolyline;
    private selectedPath;
    private navigateInfoWindow;
    private directionForward;
    private multiSelectionForward;
    private multiSelection;
    constructor();
    initialize(mapType: MapType, params: any): Promise<any>;
    loadGEOJson(data: object, options: GeoJsonOptions, eventClick: any): void;
    drawMarker(options: MarkerOptions, eventClick: any): any;
    fitBoundsPositions(markers: any[]): void;
    drawCircleMarker(options: CircleMarkerOptions, eventClick: any): any;
    toggleMarkers(markers: any[], show: boolean): void;
    alterMarkerOptions(markers: any[], options: MarkerAlterOptions): void;
    drawPolygon(options: PolygonOptions, eventClick: any): any;
    fitBoundsPolygon(polygon: any): void;
    togglePolygons(polygons: any[], show: boolean): void;
    alterPolygonOptions(polygons: any[], options: PolygonAlterOptions): void;
    drawCircle(options: CircleOptions, eventClick: any): any;
    toggleCircles(circles: any[], show: boolean): void;
    alterCircleOptions(circles: any[], options: CircleAlterOptions): void;
    drawPolyline(options: PolylineOptions, eventClick: any): any;
    togglePolyline(polyline: any, show: boolean): void;
    drawPolylineWithNavigation(options: PolylineOptions, eventClick: any): any;
    clearListenersPolyline(polyline: any): void;
    addPolylinePath(polyline: any, position: number[]): void;
    removePolylineHighlight(): void;
    alterPolylineOptions(polyline: any, options: PolylineOptions): void;
    drawPopup(options: PopupOptions): any;
    alterPopup(popup: any, options: PopupOptions): void;
    addClickMap(eventClick: any): void;
    removeClickMap(): void;
    private addNavigation;
    private onClickPolyline;
    private onKeyUp;
    private moveFowards;
    private navigateFoward;
    private moveBackwards;
    private navigateBackward;
    private moveSelectedPath;
    private checkIdx;
    private distanceToLine;
    private kmTo;
    private parseGeoJson;
    private parseGeoJsonToObject;
    private clearPolylinePath;
}
